/*
 * The MIT License
 *
 * Copyright 2019 Brian & Willian.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.edu.qi.view;

import javax.swing.JInternalFrame;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author Brian & Willian
 * @since 07/06/2019 - 18:26
 * @version 1.0
 */
public class MainMenu extends javax.swing.JFrame implements InternalFrameListener {

    private UINewClient uINewClient = null;
    private UINewBurger uINewBurger = null;
    private UIClientManager uIClientManager = null;
    private UINewOrder uiNewOrder = null;
    private UIBurgerManager burgerManager = null;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpDesktop = new javax.swing.JDesktopPane();
        jmbMenu = new javax.swing.JMenuBar();
        jmiNew = new javax.swing.JMenu();
        jmiNewClient = new javax.swing.JMenuItem();
        jmiNewBurger = new javax.swing.JMenuItem();
        jmiNewOrder = new javax.swing.JMenuItem();
        jmiEdit = new javax.swing.JMenu();
        jmiManageClients = new javax.swing.JMenuItem();
        jmiManageBurgers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brian & Willian - Java Visual Final Project");

        javax.swing.GroupLayout jdpDesktopLayout = new javax.swing.GroupLayout(jdpDesktop);
        jdpDesktop.setLayout(jdpDesktopLayout);
        jdpDesktopLayout.setHorizontalGroup(
            jdpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpDesktopLayout.setVerticalGroup(
            jdpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jmiNew.setText("New");
        jmiNew.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmiNewClient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmiNewClient.setText("New Client");
        jmiNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewClientActionPerformed(evt);
            }
        });
        jmiNew.add(jmiNewClient);

        jmiNewBurger.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmiNewBurger.setText("New Burger");
        jmiNewBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewBurgerActionPerformed(evt);
            }
        });
        jmiNew.add(jmiNewBurger);

        jmiNewOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jmiNewOrder.setText("New Order");
        jmiNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewOrderActionPerformed(evt);
            }
        });
        jmiNew.add(jmiNewOrder);

        jmbMenu.add(jmiNew);

        jmiEdit.setText("Manage");
        jmiEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmiManageClients.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiManageClients.setText("Manage Clients");
        jmiManageClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManageClientsActionPerformed(evt);
            }
        });
        jmiEdit.add(jmiManageClients);

        jmiManageBurgers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiManageBurgers.setText("Manage Burgers");
        jmiManageBurgers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManageBurgersActionPerformed(evt);
            }
        });
        jmiEdit.add(jmiManageBurgers);

        jmbMenu.add(jmiEdit);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertUINewClientToDesktop() {
        if (uINewClient == null) {
            uINewClient = new UINewClient();
            jdpDesktop.add(uINewClient);
            uINewClient.setVisible(true);
            uINewClient.addInternalFrameListener(this);
        }
    }

    private void insertUINewBurgerToDesktop() {
        if (uINewBurger == null) {
            uINewBurger = new UINewBurger();
            jdpDesktop.add(uINewBurger);
            uINewBurger.setVisible(true);
            uINewBurger.addInternalFrameListener(this);
        }
    }

    private void insertUIClientManagerToDesktop() {
        if (uIClientManager == null) {
            uIClientManager = new UIClientManager();
            jdpDesktop.add(uIClientManager);
            uIClientManager.setVisible(true);
            uIClientManager.addInternalFrameListener(this);
        }

    }

    private void insertUINewOrderToDesktop() {
        if (uiNewOrder == null) {
            uiNewOrder = new UINewOrder();
            jdpDesktop.add(uiNewOrder);
            uiNewOrder.show();
            uiNewOrder.addInternalFrameListener(this);
        }

    }

    private void insertUIBurguerManagerToDesktop() {
        if (burgerManager == null) {
            burgerManager = new UIBurgerManager();
            jdpDesktop.add(burgerManager);
            burgerManager.show();
            burgerManager.addInternalFrameListener(this);
        }

    }

    private void jmiNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewClientActionPerformed
        insertUINewClientToDesktop();
    }//GEN-LAST:event_jmiNewClientActionPerformed

    private void jmiNewBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewBurgerActionPerformed
        insertUINewBurgerToDesktop();
    }//GEN-LAST:event_jmiNewBurgerActionPerformed

    private void jmiManageClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManageClientsActionPerformed
        insertUIClientManagerToDesktop();
    }//GEN-LAST:event_jmiManageClientsActionPerformed

    private void jmiNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewOrderActionPerformed
        insertUINewOrderToDesktop();
    }//GEN-LAST:event_jmiNewOrderActionPerformed

    private void jmiManageBurgersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManageBurgersActionPerformed
        insertUIBurguerManagerToDesktop();
    }//GEN-LAST:event_jmiManageBurgersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpDesktop;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenu jmiEdit;
    private javax.swing.JMenuItem jmiManageBurgers;
    private javax.swing.JMenuItem jmiManageClients;
    private javax.swing.JMenu jmiNew;
    private javax.swing.JMenuItem jmiNewBurger;
    private javax.swing.JMenuItem jmiNewClient;
    private javax.swing.JMenuItem jmiNewOrder;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        JInternalFrame internalFrame = ife.getInternalFrame();
        if (internalFrame instanceof UIBurgerManager) {
            burgerManager = null;
        }
        if (internalFrame instanceof UINewClient) {
            uINewClient = null;
        }
        if (internalFrame instanceof UINewBurger) {
            uINewBurger = null;
        }
        if (internalFrame instanceof UIClientManager) {
            uIClientManager = null;
        }
        if (internalFrame instanceof UINewOrder) {
            uiNewOrder = null;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {

    }
}
